openapi: 3.0.0
security:
  - BearerAuth: []

info:
  title: SIMPL-Open Catalogue Search API
  description: This API is for the quick search and advanced search of Resource descriptions in the Catalogue.
  version: 1.0.6
  contact:
    name: Simpl Programme
    email: cnect-simpl@ec.europa.eu
    url: https://simpl-programme.ec.europa.eu/v1
  license:
    name: European Union Public License (EUPL) 1.2
    url: "https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf"

servers:
  - url: https://adapter.dev.simpl-europe.eu
    description: Generated server url

paths:
  /searchCatalogue/quick:
    post:
      tags:
        - search
      summary: Quick search in the Catalogue
      operationId: queryCatalogueQuickSearch
      parameters:
        - name: searchString
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Results from a quick search in the Catalogue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResultList'
              example:
                totalCount: 1
                items:
                  - item:
                    name: Example Resource
                    description: This text serves as the short description of the Example Resource
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                title: Unauthorized
                detail: The access token is missing or expired
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                title: Internal Server Error
                detail: The server encountered an unexpected condition which prevented it from fulfilling the request

  /searchCatalogue/advanced:
    post:
      tags:
        - search
      summary: Advanced search in the catalogue based on provided vocabulary
      operationId: queryCatalogueAdvancedSearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdvancedSearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResultList'
              example:
                totalCount: 1
                items:
                  item:
                    name: Example Resource
                    description: This text serves as the short description of the Example Resource
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                title: Unauthorized
                detail: The access token is missing or expired
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                title: Internal Server Error
                detail: The server encountered an unexpected condition which prevented it from fulfilling the request


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Problem:
      description: 
        A Problem Details object (RFC 9457).
        Additional properties specific to the problem type may be present.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: An absolute URI that identifies the problem type
          default: about:blank  # kept for backwards-compatibility, type will be mandatory in problem-v2
        href:
          type: string
          format: uri
          description: An absolute URI that, when dereferenced, provides human-readable documentation for the problem type (e.g. using HTML).
        title:
          type: string
          description: A short summary of the problem type. Written in English and readable for engineers (usually not suited for non technical stakeholders and not localized).
          example: Service Unavailable
        status:
          type: integer
          format: int32
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    AdvancedSearchRequest:
      type: object
      properties:
        generalServiceProperties:
          type: object
          properties:
            '@type':
              type: string
            name:
              type: string
      example:
        generalServiceProperties:
          name: Example Resource 
    SearchResultList:
      type: object
      properties:
        totalCount:
          type: integer
          description: Total number of search results
        items:
          description: List of search results
          type: array
          items:
            type: object
            properties:
              item:
                description: Individual search result
                type: object
                properties:
                  name:
                    description: Name of the resource
                    type: string
                  description:
                    description: Short descriptive text of the resource
                    type: string
                additionalProperties: true



