openapi: 3.0.3
info:
  title: Validation API
  description: OpenApi documentation for the Validation API
  version: 1.0.0
  license:
    name: European Union Public License (EUPL) 1.2
    url: https://interoperable-europe.ec.europa.eu/sites/default/files/custom-page/attachment/eupl_v1.2_en.pdf
  contact:
    name: Simpl Programme
    email: cnect-simpl@ec.europa.eu
    url: https://simpl-programme.ec.europa.eu/
servers:
  - url: https://tbd.dev.simpl-europe.eu
security:
  - bearerAuth: []
tags:
  - name: SD Validation Controller
    description: Endpoint for Self-Description (SD) validation
paths:
  /api/v1/resourceAddress/validate:
    post:
      summary: Validate a resource address JSON against a provided JSON Schema Template
      description: Receives as input a JSON containing the values of a resource address and a JSON schema template with constraints, and returns the result of the validation as output.
      tags:
        - Resource Address Validation Controller
      operationId: validateResourceAddress
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - jsonSchema
                - jsonValue
              properties:
                jsonSchema:
                  type: string
                  format: binary
                  description: JSON Schema Template file for validation
                jsonValue:
                  type: string
                  format: binary
                  description: Resource address JSON value to validate
      responses:
        '200':
          description: Validation outcome
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonValidationResponse'
              examples:
                success:
                  summary: Valid value
                  value:
                    valid: true
                failure:
                  summary: Invalid value
                  value:
                    valid: false
                    errors:
                      - message: "required key [id] not found"
                        pointer: "/"
        '400':
          description: Bad Request - Missing or malformed schema/value
        '403':
          description: Forbidden – the client does not have access rights
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
        '500':
          description: Internal Server Error
 
  /api/v1/sd/validate:
    post:
      tags:
        - SD Validation Controller
      summary: Validate the JSON-LD of a Self-Description (SD)
      description: Receives a JSON-LD file containing a Self-Description, a SHACL file for validation, and an ecosystem identifier. Returns the validated JSON-LD upon successful validation.
      operationId: validate
      parameters:
        - name: ecosystem
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - jsonldFile
                - shapeFile
              type: object
              properties:
                jsonldFile:
                  type: string
                  format: binary
                shapeFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successfully validated SD JSON-LD
          content:
            application/json:
              schema:
                type: object
              examples:
                Validated SD JSON-LD:
                  description: Validated SD JSON-LD
                  value:
                    '@context':
                      gax-validation: http://w3id.org/gaia-x/validation#
                      rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
                      sh: http://www.w3.org/ns/shacl#
                      simpl: http://w3id.org/gaia-x/simpl#
                      skos: http://www.w3.org/2004/02/skos/core#
                      xsd: http://www.w3.org/2001/XMLSchema#
                    '@id': did:web:registry.gaia-x.eu:DataOffering:12Ar124fx
                    rdf:type:
                      '@id': simpl:DataOffering
                    ...: ...
components:
  schemas:
    JsonValidationResponse:
      type: object
      required:
        - valid
      properties:
        valid:
          type: boolean
          description: Indicates if the value is valid
        errors:
          type: array
          description: List of validation errors
          items:
            type: object
            properties:
              message:
                type: string
                description: Human-readable error message
              pointer:
                type: string
                description: JSON pointer to the offending field

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
